<?php

/**
 * @file
 * This is the module wich allows the modification of beneficiary data with spouses and beneficiaries.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ccas_update_profile_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.ccas_update_profile':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Allows the modification of beneficiary data with spouses and beneficiaries.') .'</p>';
      #$output .= '<h3>' . t('Uses') . '</h3>';
      #$output .= '<p>' . t('to develop.') . '</p>';
      return $output;
  }
}
